[project]
name = "k1-walking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "plotly>=6.5.2",
    "pyqt5>=5.15.11",
    "streamlit>=1.54.0",
    "tensorboard>=2.20.0",
]
